#
###################################
# Site wide configuration
####################################
#
title: HK's Doodle blog
email: gmlrud9001@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: '' # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: HK's Doodle
  avatar: HKPARK.jpg
  job: "Data Scientist"
  bio: "Master of Statistics"
  email: gmlrud9001@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: HeeKyung-Park
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: heekyung-park-643002152
  skype: #username
  xing: #username
  instagram: hee__kyung
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
