# Site Info
title: HK's Doodle 
tagline: 'An Amateur Data Scientist '
description: 'A Blog for Data Scientist'
baseurl: ""
url: http://HeeKyung-Park.github.io
logo: '/public/HKDoodle.JPG'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: HeeKyung-Park
  description: A passionate <strong>Data Scientist</strong>, learning to be a giant.
  # gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/heekyung-park-643002152/
    github:    https://github.com/HeeKyung-Park
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  Deep learning :
    - 'DL'
    - { Contents: 'DL/contents/'}
    - { Tags: 'DL/tags/'}
  About:          
    - '/about/'


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
contents_page: 'DL/contents/'

hero:
  image: /public/robot.jpg
  caption: Original Artwork &copy; <a href='https://kr.123rf.com/profile_czarnybez'>czarnybez / 123RF 스톡 콘텐츠</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

